### Get all brews
GET http://localhost:3000/api/tea?minRating=9&page=2&pageSize=1
Accept: application/json

###

### Get brew by id
GET http://localhost:3000/api/tea/YIBmd5i5WbS6hdet1vSw4
Accept: application/json
x-api-key: im_rd_student

###

### Create brew
POST http://localhost:3000/api/tea
Content-Type: application/json
x-api-key: im_rd_student

{
  "name": "green tea",
  "origin": "china",
  "rating": 10,
  "brewTemp": 74,
  "notes": "Floral aroma"
}

###

### Update brew (replace brewId with actual value)
PUT http://localhost:3000/api/tea/YIBmd5i5WbS6hdet1vSw4
x-api-key: im_rd_student
Content-Type: application/json

{
  "name": "dark tea"
}

###

### Delete brew
DELETE http://localhost:3000/api/brews/{{brewId}}